version: "3.8"

services:

  nginx:
    container_name: app.maxkod.nginx
    image: nginx:latest
    build: './nginx/'
    ports:
      - "80:80"
    links:
      - php  
      - mysql
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./www/html:/var/www/html
    restart: unless-stopped

  php:
    container_name: app.maxkod.php
    image: php:8.0-fpm
    build: './php/'
    expose: 
       - 9000
    links:  
       - mysql
    volumes:
      - ./www/html:/var/www/html
    restart: unless-stopped

#  node:
#    image: node:19-alpine3.16
#    container_name: task.node
#    working_dir: /www/html
#    tty: true
#    volumes:
#      - ./www/html:/var/www/html
#    ports:
#      - ${EXTERNAL_NODE_PORT:-5173}:5173
#    restart: unless-stopped

  mysql:
    container_name: app.maxkod.mysql
    build: './mysql/'
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./www/html:/var/www/html
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_USER=usr
      - MYSQL_PASSWORD=pwd
    restart: unless-stopped


